config/routes.rb
Rails.application.routes.draw do

  get 'discogs/authenticate'

  get 'discogs/callback'

  get 'discogs/index'

  get 'discogs/show'

  get 'discogs/edit'

  get 'discogs/create'

  get 'discogs/update'

  root                       'static_pages#home'
  get    'releases'       => 'static_pages#releases'
  get    'subscriptions'  => 'static_pages#subscriptions'
  get    'settings'       => 'static_pages#settings'
  get    'help'           => 'static_pages#help'
  get    'contact'        => 'static_pages#contact'
  get    'signup'         => 'users#new'
  get    'profile'        => 'users#profile'
  get    'login'          => 'sessions#new'
  post   'login'          => 'sessions#create'
  delete 'logout'         => 'sessions#destroy'

  resources :users,               except: [:show]
  # resources :artists
  resources :account_activations, only:   [:edit]
  resources :password_resets,     only:   [:new, :create, :edit, :update]

end

app/views/layouts/_footer.html.haml
%footer.mdl-mini-footer
  .mdl-mini-footer--left-section
    .mdl-logo= application_title
    %ul.mdl-mini-footer--link-list
      %li= link_to "Help", help_path
      %li= link_to "Contact", contact_path
  .mdl-mini-footer--right-section
    = link_to 'Test', '#', class: "mdl-mini-footer--social-btn"
    = link_to 'Test', '#', class: "mdl-mini-footer--social-btn"
    = link_to 'Test', '#', class: "mdl-mini-footer--social-btn"

app/views/layouts/_material_wrapper.html.haml
.site
  .mdl-layout.mdl-js-layout.mdl-layout--fixed-header
    %header.mdl-layout__header
      .mdl-layout-icon
      .mdl-layout__header-row
        / Title
        %span.mdl-layout-title.navbar-app-title= link_to application_title, root_url
        / Spacer to align nav to right
        .mdl-layout-spacer
        / Navigation
        %nav.mdl-navigation
        - if logged_in?
          %img#user-menu{:src => "/images/default_photo.png", :class => "mdl-button mdl-js-button mdl-button--icon"}
          %ul.mdl-menu.mdl-menu--bottom-right.mdl-js-menu.mdl-js-ripple-effect{:for => "user-menu"}
            %li.mdl-menu__item
              %a.reset_link{:href => profile_path}Update Profile
            %li.mdl-menu__item
              = link_to "Log out", logout_path, method: "delete", class: "reset_link"
    .mdl-layout__drawer
      %span.mdl-layout-title= application_title
      %nav.mdl-navigation
        - if logged_in?
          %a.mdl-navigation__link{:href => releases_path}New Releases
          %a.mdl-navigation__link{:href => subscriptions_path}Subscriptions
          %a.mdl-navigation__link{:href => settings_path}Settings
        %a.mdl-navigation__link{:href => contact_path}Contact
        %a.mdl-navigation__link{:href => help_path}Help

    %main.mdl-layout__content
      .page-content
        - flash.each do |msg_type, msg|
          .alert{:class => "alert-#{msg_type}"}= msg
        .row
          .col-12
            = yield
        / = render 'layouts/footer'
        = debug(params) if Rails.env.development?

app/views/layouts/_shim.html.haml
/[if lt IE 9]
  %script{ :src => "//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"}
:erb
  <meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;" />

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title= full_title(yield(:title))
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    = stylesheet_link_tag "https://storage.googleapis.com/code.getmdl.io/1.0.0/material.blue_grey-red.min.css"
    = javascript_include_tag "https://storage.googleapis.com/code.getmdl.io/1.0.0/material.min.js"
    = stylesheet_link_tag "https://fonts.googleapis.com/icon?family=Material+Icons"
    = render 'layouts/shim'
  %body
    = render 'layouts/material_wrapper'
    :javascript
        componentHandler.upgradeAllRegistered();